spring:
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            javax:
                persistence:
                    validation:
                        mode: none

