server:
    port: 8080

spring:
    datasource:
        url: "jdbc:mariadb://localhost:3306/contactmgr"
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        show_sql: true
        properties:
            hibernate:
                format_sql: true
