spring:
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            javax:
                persistence:
                    validation:
                        mode: none
app:
    image-dir: D:/Project/Challengs/launch-contact-manager/etc/photos                   