server:
    port: 8080

spring:
    datasource:
        url: "jdbc:mysql://localhost/contactmgr"
        username: contactmgr
        password: contactmgr123
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        show_sql: true
        properties:
            hibernate:
                format_sql: true