spring:
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            javax:
                persistence:
                    validation:
                        mode: none
    mail:
        host: smtp.gmail.com
        username: contactmanagerlaunch@gmail.com
        password: contactmgr123
        properties:
            mail:
                smtp:
                    auth: true
                    socketFactory:
                        port: 465
                        class: javax.net.ssl.SSLSocketFactory
                        fallback: false
app:
    image-dir: D:/Project/Challengs/launch-contact-manager/etc/photos
