CREATE TABLE `users` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(100) NOT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `FIRST_NAME` varchar(45) DEFAULT NULL,
  `LAST_NAME` varchar(45) DEFAULT NULL,
  `ROLE` varchar(45) DEFAULT NULL,
  `EXPIRED_DATE` date DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  `CREATED_AT` date DEFAULT NULL,
  `CREATED_BY` varchar(100) DEFAULT NULL,
  `UPDATED_AT` date DEFAULT NULL,
  `UPDATED_BY` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `LANGUAGE` varchar(3) DEFAULT NULL,
  `ASSIGNED_COMPANIES` varchar(5000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;