CREATE TABLE IF NOT EXISTS CONTACT(
 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 FIRST_NAME VARCHAR(50) NOT NULL,
 MIDDLE_NAME VARCHAR(50),
 LAST_NAME VARCHAR(50),
 EMAIL VARCHAR(255),
 PHOTO VARCHAR(255), -- STORE URL OF PHOTO
 MOBILE VARCHAR(15),
 GENDER VARCHAR(10),
 BIRTHDAY TIMESTAMP,
 STREET VARCHAR(250),
 CITY VARCHAR(150),
 STATE VARCHAR(150),
 POSTAL_CODE INTEGER(5),
 COUNTRY VARCHAR(150),
 PHONE VARCHAR(15),
 FAX VARCHAR(20),
 TITLE VARCHAR(50),
 DEPARTMENT VARCHAR(100),
 COMPANY_ID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPANY(
 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 CODE VARCHAR(10),
 NAME VARCHAR(100) NOT NULL,
 WEBSITE VARCHAR(255),
 LOGO VARCHAR(255),
 MESSAGE VARCHAR(255),
 STREET VARCHAR(250),
 CITY VARCHAR(150),
 STATE VARCHAR(150),
 POSTAL_CODE INTEGER(5),
 COUNTRY VARCHAR(150),
 PHONE VARCHAR(15) UNIQUE,
 FAX VARCHAR(20) UNIQUE
);

ALTER TABLE CONTACT
ADD CONSTRAINT FK_CONTACT_COMPANY
FOREIGN KEY  (COMPANY_ID)
REFERENCES COMPANY(ID);
